
# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW 
# boundary pode ser qualquer nome

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="testeVideoHttp.mp3"
Content-Type: audio/mpeg

< ./testeVideoHttp.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/e95eebb5-98e0-4b29-86fc-dc9d8f81a5de/transcription
Content-Type: application/json

{
  "prompt": "protocolo http"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "e95eebb5-98e0-4b29-86fc-dc9d8f81a5de",
  "temperature": 0.5,
  "template": "Gere um resumo sucinto da transcrição do video informada a seguir: ''' {transcription} ''' "
}